version: "3"
services:
  database:
    image: "kartoza/postgis"
    container_name: "database"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
volumes:
  my_dbdata:
